version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_DATABASE: laravel_test
          - MYSQL_ROOT_PASSWORD: secret
    environment:
      - DB_HOST: 127.0.0.1
    steps:
      - checkout
      - run: composer install -n --prefer-dist --working-dir=./backend
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo composer self-update
      # - run: npm ci --working-dir=./backend
      # - run: npm run dev --working-dir=./backend
      - run: php ./backend/artisan --env=testing
      - run: php ./backend/vendor/bin/phpunit --configuration=./backend/phpunit.xml