version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_DATABASE: laravel_test
          - MYSQL_ROOT_PASSWORD: secret
    environment:
      - DB_HOST: 127.0.0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./backend/composer.lock" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist --working-dir=./backend
      - save_cache:
          key: composer-v1-{{ checksum "./backend/composer.lock" }}
          paths:
            - ./backend/vendor
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo composer self-update
      - run: php ./backend/artisan --env=testing
      - run: php ./backend/vendor/bin/phpunit --configuration=./backend/phpunit.xml
